include: package:lints/recommended.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true