name: minidart_compiler_web
description: MiniDart Compiler Web Interface v1.4.1
version: 1.4.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.7
  build_web_compilers: ^4.0.7
